# Generated by Django 5.2.8 on 2025-11-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moisture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Weed_impurity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Oil_impurity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Oil_content', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KCHM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Protein', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
