# Generated by Django 5.2.8 on 2025-11-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovalForSunflower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moisture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Weed_impurity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Oil_impurity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Oil_content', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KCHM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Protein', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Removal',
            new_name='RemovalForRapeseed',
        ),
    ]
