# Generated by Django 5.2.8 on 2025-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0002_removalforsunflower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='KCHM',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='Moisture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='Oil_content',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='Oil_impurity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='Protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='Weed_impurity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='KCHM',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='Moisture',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='Oil_content',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='Oil_impurity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='Protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='Weed_impurity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
