# Generated by Django 5.2.8 on 2025-11-11 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0003_alter_removalforrapeseed_kchm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='Moisture',
            new_name='moisture',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='Oil_content',
            new_name='oil_content',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='Oil_impurity',
            new_name='oil_impurity',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='Protein',
            new_name='protein',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='Weed_impurity',
            new_name='weed_impurity',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='Moisture',
            new_name='moisture',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='Oil_content',
            new_name='oil_content',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='Oil_impurity',
            new_name='oil_impurity',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='Protein',
            new_name='protein',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='Weed_impurity',
            new_name='weed_impurity',
        ),
    ]
