# Generated by Django 5.2.8 on 2025-11-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0004_rename_moisture_removalforrapeseed_moisture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='KCHM',
            new_name='KCHM_base',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='moisture',
            new_name='KCHM_removal',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='oil_content',
            new_name='moisture_base',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='oil_impurity',
            new_name='moisture_removal',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='protein',
            new_name='oil_content_base',
        ),
        migrations.RenameField(
            model_name='removalforrapeseed',
            old_name='weed_impurity',
            new_name='oil_content_removal',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='KCHM',
            new_name='KCHM_base',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='moisture',
            new_name='KCHM_removal',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='oil_content',
            new_name='moisture_base',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='oil_impurity',
            new_name='moisture_removal',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='protein',
            new_name='oil_content_base',
        ),
        migrations.RenameField(
            model_name='removalforsunflower',
            old_name='weed_impurity',
            new_name='oil_content_removal',
        ),
        migrations.AddField(
            model_name='removalforrapeseed',
            name='oil_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforrapeseed',
            name='oil_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforrapeseed',
            name='protein_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforrapeseed',
            name='protein_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforrapeseed',
            name='weed_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforrapeseed',
            name='weed_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforsunflower',
            name='oil_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforsunflower',
            name='oil_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforsunflower',
            name='protein_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforsunflower',
            name='protein_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforsunflower',
            name='weed_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='removalforsunflower',
            name='weed_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
