# Generated by Django 5.2.8 on 2025-11-11 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0006_alter_removalforrapeseed_kchm_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='KCHM_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='КЧМ (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='KCHM_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='КЧМ (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='moisture_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Влажность (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='moisture_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Влажность (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='oil_content_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличность (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='oil_content_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличность (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='oil_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличная примесь (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='oil_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличная примесь (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='protein_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Протеин (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='protein_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Протеин (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='weed_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Сорность (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforrapeseed',
            name='weed_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Сорность (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='KCHM_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='КЧМ (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='KCHM_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='КЧМ (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='moisture_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Влажность (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='moisture_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Влажность (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='oil_content_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличность (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='oil_content_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличность (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='oil_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличная примесь (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='oil_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличная примесь (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='protein_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Протеин (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='protein_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Протеин (коэффициент съема)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='weed_impurity_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Сорность (базовое значение, %)'),
        ),
        migrations.AlterField(
            model_name='removalforsunflower',
            name='weed_impurity_removal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Сорность (коэффициент съема)'),
        ),
    ]
