# Generated by Django 5.2.8 on 2025-11-11 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0007_alter_removalforrapeseed_kchm_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Закупочная ценаб руб/кг')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Вес не может быть отрицательным.')], verbose_name='Вес партии, тонн')),
                ('moisture_actual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Влажность факт, %')),
                ('weed_impurity_actual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Сорность факт, %')),
                ('oil_impurity_actual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличная примесь факт, %')),
                ('oil_content_actual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличность факт, %')),
                ('KCHM_actual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='КЧМ факт, %')),
                ('protein_actual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Протеин факт, %')),
            ],
        ),
    ]
