# Generated by Django 5.2.8 on 2025-11-11 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0008_rawmaterialbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='KCHM_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='КЧМ факт, %'),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='moisture_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Влажность факт, %'),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='oil_content_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличность факт, %'),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='oil_impurity_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Масличная примесь факт, %'),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='protein_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Протеин факт, %'),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='weed_impurity_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Сорность факт, %'),
        ),
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Вес не может быть отрицательным.')], verbose_name='Вес партии, тонн'),
        ),
    ]
