# Generated by Django 5.2.8 on 2025-11-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0009_alter_rawmaterialbatch_kchm_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='culture',
            field=models.CharField(choices=[('raps', 'Рапс'), ('sunflower', 'Подсолнечник')], default='new', max_length=20),
        ),
    ]
