# Generated by Django 5.2.8 on 2025-11-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0011_alter_rawmaterialbatch_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='culture',
            field=models.CharField(choices=[('raps', 'Рапс'), ('sunflower', 'Подсолнечник')], default='Рапс', max_length=20),
        ),
    ]
