# Generated by Django 5.2.5 on 2025-11-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0012_alter_rawmaterialbatch_culture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='weight',
            new_name='weight_actual',
        ),
    ]
