# Generated by Django 5.2.8 on 2025-11-17 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0013_rename_weight_rawmaterialbatch_weight_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='agreementType',
            field=models.CharField(choices=[('Prepayment', 'Предоплата'), ('Postpayment', 'Постоплата')], default='Prepayment', max_length=30),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='contractType',
            field=models.CharField(choices=[('FZV', 'ФЗВ'), ('ZCHT', 'ЗЧТ'), ('ZCHC', 'ЗЧЦ')], default='FZV', max_length=30),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='delayDays',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Окончание приемки сырья'),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='partnerType',
            field=models.CharField(choices=[('Trader', 'Трейдер'), ('Farm', 'СХТП'), ('Agroholding', 'Агрохолдинг')], default='Trader', max_length=30),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='purchaseType',
            field=models.CharField(choices=[('DirectSupply', 'Прямая поставка'), ('ElevatorSupply', 'Поставка на элеватор'), ('InventoryF13', 'Перепись  Ф - 13')], default='Прямая поставка', max_length=30),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='receiptEndDate',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание приемки сырья'),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='receiptStartDate',
            field=models.DateField(blank=True, null=True, verbose_name='Начало приемки сырья'),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='targetFactory',
            field=models.CharField(choices=[('AMPZ', 'АМПЗ'), ('DMEZ', 'ЭМЭЗ'), ('EMEZ', 'ДМЭЗ'), ('VHEMEZ', 'ВХМЭЗ'), ('BKMEZ', 'БКМЭЗ'), ('BLMEZ', 'БЛМЭЗ'), ('OMEZ', 'ОМЭЗ')], default='AMPZ', max_length=30),
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='transportType',
            field=models.CharField(choices=[('Auto', 'Авто'), ('Railway', 'ЖД')], default='Auto', max_length=30),
        ),
    ]
