# Generated by Django 5.2.8 on 2025-11-17 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0014_rawmaterialbatch_agreementtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='agreementType',
            new_name='agreement_type',
        ),
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='contractType',
            new_name='contract_type',
        ),
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='partnerType',
            new_name='partner_type',
        ),
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='purchaseType',
            new_name='purchase_type',
        ),
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='receiptEndDate',
            new_name='receipt_end_date',
        ),
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='receiptStartDate',
            new_name='receipt_start_date',
        ),
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='targetFactory',
            new_name='target_factory',
        ),
        migrations.RenameField(
            model_name='rawmaterialbatch',
            old_name='transportType',
            new_name='transport_type',
        ),
        migrations.RemoveField(
            model_name='rawmaterialbatch',
            name='delayDays',
        ),
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='delay_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30, message='Значение не может быть больше 30 дней')], verbose_name='Окончание приемки сырья'),
        ),
    ]
