# Generated by Django 5.2.8 on 2025-11-17 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0015_rename_agreementtype_rawmaterialbatch_agreement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterialbatch',
            name='delay_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30, message='Значение не может быть больше 30 дней')], verbose_name='Отсрочка'),
        ),
    ]
