# Generated by Django 5.2.8 on 2025-11-18 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0016_alter_rawmaterialbatch_delay_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Расстояние, КМ ')),
                ('tariff', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Тариф, р/тн/км')),
                ('storage_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='начение не может быть отрицательным')], verbose_name='Срок хранения, дней')),
                ('acceptance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Стоимость приемки, р/тн')),
                ('storage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Стоимость хранения, р/тн/сут')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Стоимость отгрузки, р/тн')),
                ('natural_loss_pct', models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Естественная убыль, %')),
            ],
        ),
    ]
