# Generated by Django 5.2.8 on 2025-11-27 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal_rates', '0017_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialbatch',
            name='key_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Значение не может быть отрицательным.')], verbose_name='Ключевая ставка, %'),
        ),
    ]
